### ISSUE TITLE
docker image 和 cgo 的交叉依赖无关么？

### ISSUE THREAD

**Issue by DeathPoem** [vearne/passwordbox#9]
我看makefile 没有发现cgo 和交叉编译的内容，可是 mattn/go-sqlite3 应该需要cgo 才对，你是怎么做到交叉编译的？还是我理解错了？

**Comment by vearne** [comment]
哈哈，你可以看下我的文章
利用DOCKER实现GOLANG程序的交叉编译
http://vearne.cc/archives/39368

因为我的linux下的bin文件是在docker中(linux 环境)编译的，所以没有任何问题。
